### ISSUE TITLE
Is the repo end-of-life?

### ISSUE THREAD

**Issue by TAbdiukov** [google/webbundle#7]
Asking because multiple sources claim that Google no longer pursues WebBundles functionality,
* https://bugs.chromium.org/p/chromium/issues/detail?id=1040752
* https://github.com/GoogleChrome/web.dev/pull/9579
* https://web.dev/web-bundles/

**Comment by hayatoito** [comment]
> Asking because multiple sources claim that Google no longer pursues WebBundles functionality,

I believe you are referring to a statement that seems a bit exaggerated. :) 
It states that Google is no longer pursuing the functionality of WebBundles, but this may not be entirely accurate. Multiple sources only mention the "Navigate-to-WebBundles" and "Save-As-WebBundles" features, which were never actually shipped in Chrome. It is not practical to keep code for features that are unlikely to be shipped in the near future.

This repository is not directly related to those particular use cases of the Web Bundles format. 

It is worth noting that Chrome still supports the feature of [Subresource Loading with Web Bundles](https://github.com/WICG/webpackage/blob/main/explainers/subresource-loading.md), as well as the underlying Web Bundles format.

**Comment by TAbdiukov** [comment]
That's good to hear! I'd love for there to be  "Save-As-WebBundles" functionality, because it would revolutionise the web (in my opinion)

Anyway, feel free to close this issue

**Comment by hayatoito** [comment]
OK. Let me close this issue. Thanks!

**Comment by guest271314** [comment]
> I'd love for there to be "Save-As-WebBundles" functionality, because it would revolutionise the web (in my opinion)

I'm working on creating Signed Web Bundles in the browser over here https://github.com/guest271314/webbundle.

The challenge so far is that wbn-sign depends on Node.js `crypto` implementation https://github.com/GoogleChromeLabs/webbundle-plugins/issues/11#issuecomment-1847224287, which is not the same as Web Cryptograohy API implementation.
